/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "rtl/not_gate_dataflow.v:1.1-8.10" *)
module not_gate_dataflow(a, y);
  (* src = "rtl/not_gate_dataflow.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "rtl/not_gate_dataflow.v:3.12-3.13" *)
  output y;
  wire y;
  assign y = ~(* src = "rtl/not_gate_dataflow.v:6.12-6.14" *) a;
endmodule
