/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "02_rtl/xor_gate_dataflow.v:1.1-9.10" *)
module xor_gate_dataflow(A, B, Y);
  (* src = "02_rtl/xor_gate_dataflow.v:2.11-2.12" *)
  input A;
  wire A;
  (* src = "02_rtl/xor_gate_dataflow.v:3.11-3.12" *)
  input B;
  wire B;
  (* src = "02_rtl/xor_gate_dataflow.v:4.12-4.13" *)
  output Y;
  wire Y;
  assign Y = A ^(* src = "02_rtl/xor_gate_dataflow.v:7.12-7.17" *)  B;
endmodule
